# https://decapcms.org/docs/configuration-options/
backend:
  name: azure
  repo: blogorg01/blogPrj/blogPrj
  branch: main
  app_id: 933bf722-5f09-4455-aef9-aa48a4b63d55
  tenant_id: 0fdae3a8-ac40-4e2b-abdd-0135eac78f38
media_folder: "source/images"
public_folder: "/images"
site_url: "https://blog.whema.net"
logo_url: ""
locale: "zh_Hans"
common_col_conf: &common_col_conf
  create: true
  slug: "{{fields.filename}}"
  sortable_fields:
    - "commit_date"
    - "title"
    - "date"
    - "updated"
  # https://decapcms.org/docs/widgets/
  fields:
    - label: "文件名"
      name: "filename"
      widget: "string"
    - label: "标题"
      name: "title"
      widget: "string"
    - label: "发表日期"
      name: "date"
      widget: "datetime"
      format: "YYYY-MM-DD HH:mm:ss"
      date_format: "YYYY-MM-DD"
      time_format: "HH:mm:ss"
    - label: "更新日期"
      name: "updated"
      widget: "datetime"
      format: "YYYY-MM-DD HH:mm:ss"
      date_format: "YYYY-MM-DD"
      time_format: "HH:mm:ss"
      required: false
    - label: "封面"
      name: "cover"
      widget: "image"
      required: false
    - label: "缩略图"
      name: "thumbnail"
      widget: "image"
      required: false
    - label: "标签"
      name: "tags"
      widget: "select"
      multiple: true
      required: false
      options:
        - "azure"
        - "cdn"
        - "devops"
        - "docker"
        - "git"
        - "github"
        - "hexo"
        - "icarus"
        - "twikoo"
    - label: "分类"
      name: "categories"
      widget: "select"
      multiple: true
      required: false
      options:
        - "博客搭建"
        - "猫窝"
        - "叨咕叨咕"
        - "捣鼓捣鼓"
        - "溜达溜达"
        - "猫图秀秀"
    - label: "正文"
      name: "body"
      widget: "markdown"
    - label: "原创"
      name: "toc"
      widget: "boolean"
      default: true
    - label: "评论"
      name: "comments"
      widget: "boolean"
      default: true
collections:
  - name: "2023"
    label: "2023"
    folder: "source/_posts/2023"
    preview_path: "2023/{{filename}}/"
    <<: *common_col_conf
